### PR TITLE
Added ads to the project

### PR DESCRIPTION
**Pull request by davidgatti**
Added ads

Issue(s): #16

### CODE REVIEW

**Comment by davidgatti** [comment]
@tolgaouz I added the ads, but this is not working:

- the images are not being displayed
- the tittle is not being displayed.

**Comment by tolgaouz** [comment]
The reason images are not displayed is probably because AdBlocker or such kind of program is active. ( Tested both on my Windows and Mac, was able to see them)

- How should I display title ?

ads

**Comment by davidgatti** [comment]
Yes, title is required :) and I see I made a

**Comment by tolgaouz** [comment]
I added the title

**Pull request merged**
