### PR TITLE
UI Changes - Issue: #7

### PR DESCRIPTION
**Pull request by tolgaouz**
- EC2 has been populated to have data from 2018 - 2019 - 2020
- Made other changes.

### CODE REVIEW

**Comment by davidgatti** [comment]
Screen Shot 2020-07-17 at 9 42 26 AM

**Comment by tolgaouz** [comment]
EC2 is populated with more years, I mentioned it in the description. Haven't applied more years to all services just yet

**Comment by tolgaouz** [comment]
I can make the resolution like it was before I didn't notice it was changed :/

**Comment by davidgatti** [comment]
- Yes @tolgaouz you should change it back ;) 
- not 50% take a moment to think what would be the best thing to do.

**Comment by davidgatti** [comment]
@tolgaouz check the conflict.

**Pull request merged**
